# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - API_END_POINT=${API_END_POINT}
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file: .env

networks:
  app-network:
    driver: bridge
      #dummy
